version: 2.1
executors:
  build_executor:
    docker:
      - image: cirrusci/flutter:3.0.0
commands:
  cmd_build_and_release:
    steps:
      - run: 
          name: Build and release new version
          command: |
            sudo apt update -y
            sudo apt install bash
            wget https://dl.google.com/go/go1.19.3.linux-amd64.tar.gz
            sudo tar -C /usr/local/ -xzf ./go1.19.3.linux-amd64.tar.gz
            export PATH=$PATH:/usr/local/go/bin
            export PATH=$PATH:~/go/bin
            go version
            go install github.com/tcnksm/ghr@latest
            cd ~/go/bin && ls -la && ghr -v

jobs:
  build_and_release:
    executor: build_executor
    steps:
      - checkout
      - cmd_build_and_release

workflows:
  my-workflow:
    jobs:
      - build_and_release
